#!/usr/bin/env bash
# Affichage des connexions Internet actives (seulement les serveurs)
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -tuln -p | grep LISTEN

echo ""
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -x -p | grep LISTEN
