#!/usr/bin/env bash
# check if the numbers of args is equal to 0 if true display a message,
# else repeat 5 time the command ping with the passed argument
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$1"
