#!/bin/bash

# Vérifier si un argument a été passé
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# L'argument passé est l'adresse IP à pinger
IP_ADDRESS=$1

# Exécuter la commande ping 5 fois
ping -c 5 "$IP_ADDRESS"
