#!/usr/bin/env bash
# Backup the original /etc/hosts file before making changes
sudo cp /etc/hosts /etc/hosts.bak
# Modify the /etc/hosts file
sudo sed -i 's/^127.0.0.1.*localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
# Display the updated /etc/hosts file to confirm changes
cat /etc/hosts
